# Site settings
title: An Exciting Journey ! 
header-img: img/home-bg.png
email: nichia@gmail.com
copyright_name: nichia
description: > # this means to ignore newlines until "baseurl:"
  With Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nichia
learn_profile: nichia
email_username: nichia@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
