# Site settings
author: Ni Chia
title: An Exciting Journey! 
header-img: img/home-bg.png
email: nichia@gmail.com
copyright_name: Ni Chia
description: > # this means to ignore newlines until "baseurl:"
  with Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nichia

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
